Add proper postinst routine, also udev, modprobe

diff --git a/debian/cryptodev.postinst b/debian/cryptodev.postinst
--- a/debian/cryptodev.postinst
+++ b/debian/cryptodev.postinst
@@ -1,5 +1,44 @@
-#!/bin/sh -e
+#!/bin/sh
+# postinst script for cryptodev
+#
+# see: dh_installdeb(1)
 
-depmod -a
+set -e
+
+# summary of how this script can be called:
+#        * <postinst> `configure' <most-recently-configured-version>
+#        * <old-postinst> `abort-upgrade' <new version>
+#        * <conflictor's-postinst> `abort-remove' `in-favour' <package>
+#          <new-version>
+#        * <postinst> `abort-remove'
+#        * <deconfigured's-postinst> `abort-deconfigure' `in-favour'
+#          <failed-install-package> <version> `removing'
+#          <conflicting-package> <version>
+# for details, see http://www.debian.org/doc/debian-policy/ or
+# the debian-policy package
 
 #DEBHELPER#
+
+case "$1" in
+    configure)
+
+#instant setup, so no reboot is necessary
+    mod_ver=$(modinfo -F vermagic cryptodev | cut -f 1 -d ' ');
+    if [ "$(uname -r)" = "$mod_ver" ]; then
+	    if modprobe cryptodev; then
+		    chmod go+rw /dev/crypto || true;
+	    fi
+    fi
+
+    ;;
+
+    abort-upgrade|abort-remove|abort-deconfigure)
+    ;;
+
+    *)
+        echo "postinst called with unknown argument \`$1'" >&2
+        exit 1
+    ;;
+esac
+
+exit 0
